site_name: slicemap
repo_url: https://github.com/gahaalt/slicemap

nav:
    - Home: README.md
    - quick_start.md
    - applications.md
    - api.md



plugins:
    - search
    - autorefs
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  options:
                      docstring_style: numpy

theme:
    name: material

    palette:

        # Palette toggle for light mode
        -   scheme: default
            toggle:
                icon: material/brightness-7
                name: Switch to dark mode

        # Palette toggle for dark mode
        -   scheme: slate
            toggle:
                icon: material/brightness-4
                name: Switch to light mode
